### ISSUE TITLE
MultiplexGNN misnomer

### ISSUE THREAD

**Issue by nashapir** [lujiaying/MUG-Bench#10]
Hello,

There are a couple of places in the code where i believe ```MultiplexGNN``` is mistakenly used instead of ```MuGNet```.  This should be all of them: https://github.com/search?q=repo%3Alujiaying%2FMUG-Bench%20MultiplexGNN&type=code. My suspicion is that they can all just be changed to ```MuGNet``` and the code works great then.

Cheers!

**Comment by lujiaying** [comment]
Thanks nashpir,

I quickly went through the code, and made a fix at 59a2ac6
Appreciate your help.

Best,
Jiaying
